services:
  app:
    build: .
    container_name: takumap-be
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["java", "-jar", "app.jar"]

  mysql:
    image: mysql:8.0
    container_name: takumap-db
    ports:
      - "3307:3306"
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data: