spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/google
            scope: email, profile

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  header: ${HEADER}
  secret: ${SECRET_KEY}
  token-validity-in-seconds: 86400

cloud:
  aws:
    s3:
      bucket-name: "takumap-local-storage"
      endpoint: "http://mysql:9000"
    credentials:
      access-key: minioadmin
      secret-key: minioadmin